name: EspectralUHC_Clases
version: '${project.version}'
main: net.mmf55dev.uhcclases.EspectralClassUHC
api-version: '1.20'
commands:
  class:
    description: "Main Commands from Espectral UHC Clases Scenario"