name: EspectralUHC_Clases
version: '1.5.1-SNAPSHOT'
main: net.mmf55dev.uhcclases.EspectralClassUHC
api-version: '1.20'
depend: [ProtocolLib]
commands:
  class:
    description: "Main Commands from Espectral UHC Clases Scenario"